//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
      const int limiter = 4000000;
      int[] sequence = new int[limiter];
      int fibonacci = 1;

      for (int i = 0; i < limiter; i++)
      {
        if (i == 0)
        {
          sequence[i] = fibonacci;
        }
        else if (i == 1)
        {
          sequence[i] = (fibonacci + 1);
        }
        else
        {
          sequence[i] = (sequence[(i-1)] + sequence[(i-2)]);
        }
      }

        int evens = 0;
        foreach (int evenNums in sequence)
        {
          if (evenNums % 2 == 0)
          {
            evens += evenNums;
          }
        }
